package com.mycompany.troklos.businesslayer;
// Generated 15-ene-2018 13:15:53 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Privileges generated by hbm2java
 */
public class Privileges  implements java.io.Serializable {


     private Integer idprivileges;
     private String name;
     private Set users = new HashSet(0);

    public Privileges() {
    }

	
    public Privileges(String name) {
        this.name = name;
    }
    public Privileges(String name, Set users) {
       this.name = name;
       this.users = users;
    }
   
    public Integer getIdprivileges() {
        return this.idprivileges;
    }
    
    public void setIdprivileges(Integer idprivileges) {
        this.idprivileges = idprivileges;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }

    @Override
    public String toString() {
        return "Privileges{" + "idprivileges=" + idprivileges + ", name=" + name + '}';
    }

    
}


