package com.mycompany.troklos.businesslayer;
// Generated 15-ene-2018 13:15:53 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIdentityReference;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;










/**
 * Request generated by hbm2java
 */
public class Request  implements java.io.Serializable {

    @JsonProperty("idrequest")
     private int idrequest;
     @JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property="iduser")
     @JsonIdentityReference(alwaysAsId=true)
     private User user;
     private String description;
     private String requestDate;
     private String expDate;
     private int status;

    public Request() {
    }

    public Request(int idrequest, User user, String description, String requestDate, String expDate, int status) {
       this.idrequest = idrequest;
       this.user = user;
       this.description = description;
       this.requestDate = requestDate;
       this.expDate = expDate;
       this.status = status;
    }
   
    public int getIdrequest() {
        return this.idrequest;
    }
    
    public void setIdrequest(int idrequest) {
        this.idrequest = idrequest;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getRequestDate() {
        return this.requestDate;
    }
    
    public void setRequestDate(String requestDate) {
        this.requestDate = requestDate;
    }
    public String getExpDate() {
        return this.expDate;
    }
    
    public void setExpDate(String expDate) {
        this.expDate = expDate;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return "Request{" + "idrequest=" + idrequest + ", user=" + user + ", description=" + description + ", requestDate=" + requestDate + ", expDate=" + expDate + ", status=" + status + '}';
    }

    
}


