package com.mycompany.troklos.businesslayer;
// Generated 15-ene-2018 13:15:53 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIdentityReference;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {

     @JsonProperty("iduser")
     private Integer iduser;
     @JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property="idprivileges")
     @JsonIdentityReference(alwaysAsId=true)
     private Privileges privileges;
     private String name;
     private String surname;
     private String email;
     private String postalCode;
     private String city;
     private String region;
     private String country;
     private String password;
     @JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property="idrequest")
     @JsonIdentityReference(alwaysAsId=true)
     private Set requests = new HashSet(0);

    public User() {
    }

	
    public User(Privileges privileges, String name, String surname, String email) {
        this.privileges = privileges;
        this.name = name;
        this.surname = surname;
        this.email = email;
    }
    public User(Privileges privileges, String name, String surname, String email, String postalCode, String city, String region, String country, String password, Set requests) {
       this.privileges = privileges;
       this.name = name;
       this.surname = surname;
       this.email = email;
       this.postalCode = postalCode;
       this.city = city;
       this.region = region;
       this.country = country;
       this.password = password;
       this.requests = requests;
    }
   
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
    public Privileges getPrivileges() {
        return this.privileges;
    }
    
    public void setPrivileges(Privileges privileges) {
        this.privileges = privileges;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getRequests() {
        return this.requests;
    }
    
    public void setRequests(Set requests) {
        this.requests = requests;
    }

    @Override
    public String toString() {
        return "User{" + "iduser=" + iduser + ", name=" + name + ", surname=" + surname + ", email=" + email + ", postalCode=" + postalCode + ", city=" + city + ", region=" + region + ", country=" + country + ", password=" + password + '}';
    }

    
}


